name: Nightly Build
on:
  # keep this separate from regular build, as GitHub will disable scheduled builds after 30 days
  # without a change (and won't enable them automatically, for example on pushed changes or pull requests)
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    strategy:
      max-parallel: 2
      matrix:
        java:
          - '1.8'
          - '11.0.5'
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - os: macos-latest
            java: '1.8'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          ./gradlew -S -Pskip.signing assemble
          ./gradlew -S -Pskip.signing check
      - name: Upstream Build
        if: matrix.os == 'ubuntu-latest' && matrix.java == '8'
        run: |
          test-asciidoctor-upstream.sh


